### ISSUE TITLE
Add an Http client to the native erc20 fetcher 

### ISSUE THREAD

**Issue by jrchatruc** [lambdaclass/zksync-era#187]
### 🌟 Feature Request

The `NativeErc20Fetcher` is currently creating a new http client each time it makes a request. It should instead keep one in a field that's initialized on startup and then use that each time.

Reference: https://github.com/matter-labs/zksync-era/pull/996#discussion_r1500257377

**Comment by juan518munoz** [comment]
[Closed here](https://github.com/matter-labs/zksync-era/pull/1263)
