### ISSUE TITLE
Make the Erc20 Fetcher mandatory and have a no-op implementation that always returns 1

### ISSUE THREAD

**Issue by jrchatruc** [lambdaclass/zksync-era#192]
### 🌟 Feature Request

Instead of making the `Erc20Fetcher` an option (where it only runs in the case of a non-eth base token), make it mandatory and add a default No-Op implementation that always returns `Ok(1)` in the case where `eth` is the native token.

**Comment by juan518munoz** [comment]
[Merged PR](https://github.com/matter-labs/zksync-era/pull/1272)
