### ISSUE TITLE
Improve Fetcher Error Handling

### ISSUE THREAD

**Issue by jrchatruc** [lambdaclass/zksync-era#193]
### 🌟 Feature Request

Currently, if a network request to the conversion rate API fails the component (and thus the entire server) goes down.

We should improve our error handling with the following logic. If the request returns an error, then:

- Do not break out of the loop, instead emit a `tracing::error!(..)` message and keep going.
- Keep count of the amount of times a network error has occurred in a row.
- If the error count exceeds 10 times, emit a Sentry error (via `vlog::capture_message`). It will trigger an alert for any configured setup.

**Comment by juan518munoz** [comment]
[Merged PR](https://github.com/matter-labs/zksync-era/pull/1282)
