### ISSUE TITLE
Replace unwraps with `anyhow::Errors` in the `NativeTokenFetcher` methods

### ISSUE THREAD

**Issue by jrchatruc** [lambdaclass/zksync-era#195]
### 🌟 Feature Request

The `new` method should return an `anyhow::Result<Self>`, and the errors should have (anyhow::)context added to them.

The same goes for the `run` method (the "main loop" of the task)

**Comment by SantiagoPittella** [comment]
It is addressed in:

https://github.com/matter-labs/zksync-era/pull/1298
