### ISSUE TITLE
Modify the conversion rate API the fetcher hits to include the base token address

### ISSUE THREAD

**Issue by jrchatruc** [lambdaclass/zksync-era#198]
### 🌟 Feature Request

The endpoint now becomes `/conversion_rate/{base_token_address}`
The fetcher should get the value of the base token address from configuration

**Comment by SantiagoPittella** [comment]
Addressed at: https://github.com/matter-labs/zksync-era/pull/1301

**Comment by juan518munoz** [comment]
[Merged PR](https://github.com/matter-labs/zksync-era/pull/1301)
