### ISSUE TITLE
Use `BigDecimal` to make the calculations for the conversion rate

### ISSUE THREAD

**Issue by jrchatruc** [lambdaclass/zksync-era#201]
### 🌟 Feature Request

The conversion rate variable is right now a `u64`, which does not account for fractionary ratios. To solve this, move it to be a [BigDecimal](https://docs.rs/bigdecimal/latest/bigdecimal/) type (essentially an arbitrary precision rational number) and do the calculations accordingly. 

Check [this implementation](https://github.com/matter-labs/zksync/blob/master/core/bin/zksync_api/src/fee_ticker/mod.rs) for reference on how to do it.

**Comment by juan518munoz** [comment]
[Closed here](https://github.com/lambdaclass/zksync-era/pull/204)
