### ISSUE TITLE
Validate Pubdata Cost Consistency in Validium Mode

### ISSUE THREAD

**Issue by ilitteri** [lambdaclass/zksync-era#50]
## Integration Test: Validate Pubdata Cost Consistency in Validium Mode

**Description:**
Create an integration test to validate that the cost of processing a transaction with 0 pubdata is equivalent to the cost of a transaction with the maximum pubdata size in Validium mode. This test aims to ensure that the processing cost remains consistent regardless of pubdata size, contributing to fair and predictable transaction fees.

**Test Steps:**
1. Set up the system in Validium mode.
2. Generate a transaction with 0 pubdata.
3. Record the gas usage and associated cost for the transaction.
4. Generate a transaction with the maximum allowed pubdata size.
5. Record the gas usage and associated cost for the transaction.
6. Compare the processing costs of the two transactions.

**Expected Outcome:**
- The cost of processing a transaction with 0 pubdata should be equivalent to the cost of a transaction with the maximum pubdata size in Validium mode.
- Gas usage and associated costs should be consistent, irrespective of pubdata size.
- This test ensures fair and predictable transaction fees in Validium mode.

**Comment by mationorato** [comment]
Done
