### ISSUE TITLE
Make the stack initialization mode (Rollup or Validium) part of state keeper's config

### ISSUE THREAD

**Issue by ilitteri** [lambdaclass/zksync-era#89]
As commented [here](https://github.com/lambdaclass/zksync-era/pull/75#discussion_r1474245028), we should have a proper config for selecting which committer mode will be instantiated.

It was agreed to add a config to the state keeper. This should be done in the `chain.toml` (`chain.state_keeper` section) and then we should reflect the changes in the `StateKeeperConfig`'s implementation.

**Comment by mationorato** [comment]
closed by #94
