### ISSUE TITLE
`--validium-mode` flag should set Validium config in `chain.toml`

### ISSUE THREAD

**Issue by ilitteri** [lambdaclass/zksync-era#96]
Today we're setting some configs manually in the `chain.toml`. These should be set automatically depending on whether the `--validium-mode` flag is set to `true` or not. This logic should be encapsulated in a function and executed in the `init.ts` script for the `init`, `reinit`, and `lightweightInit` commands.

> For this, we should branch from `feat_validium_pubdata_abstraction`.

**Comment by toni-calvin** [comment]
There is a similar approach for doing this  fixing the integration tests in this pr: #82
